In [3]:
import torch
import numpy as np

LISTS

In [6]:
my_list = [1,2,3,4,5]
my_list = [[1,2,3,4,5],[6,7,8,9]]

my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

NUMPY ARRAYS

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.7498285 , 0.74653126, 0.15004457, 0.55845683],
       [0.3363961 , 0.41466275, 0.59339528, 0.09891213],
       [0.50962316, 0.95727789, 0.11440055, 0.46412776]])

In [10]:
np1.dtype

dtype('float64')

TENSORS

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5760,  0.0843,  0.5069,  1.2737],
        [ 0.2068,  0.2316, -0.7895, -1.4637],
        [ 0.0617, -0.9155, -0.3199,  1.4891]])

In [13]:
tensor_2d.dtype

torch.float32

In [14]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7498, 0.7465, 0.1500, 0.5585],
        [0.3364, 0.4147, 0.5934, 0.0989],
        [0.5096, 0.9573, 0.1144, 0.4641]], dtype=torch.float64)