In [2]:
import torch
import numpy as np
# Learning to do the following with tensors:
# addition
# subtraction 
# multiplication
# division 
# modulo
# exponents
# add_ to add a tensor to an existing tensor then reassign the new value to the main tensor

In [23]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [6]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
# Multiply longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Div Longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
# Remainder Modulus
tensor_b % tensor_a


tensor([0, 0, 1, 0])

In [17]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [18]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a.add_(tensor_b)
# add_ is to add tensor_b to tensor_a and then reassign this value to tensor_a

tensor([ 6,  8, 10, 12])

In [26]:
tensor_a

tensor([ 6,  8, 10, 12])